talent_homepage:
    path:     /home
    defaults: { _controller: TalentBundle:Default:index }
list_video:
    path: /admin/list_video
    defaults: {_controller: TalentBundle:Video:viewVideo}
add_video:
    path: /profile/add_video
    defaults: {_controller: TalentBundle:Video:addVideo}
delete_video:
    path: /admin/delete/{id}
    defaults : { _controller: TalentBundle:Video:delete}
update_video:
    path: /admin/update/{id}
    defaults: { _controller: TalentBundle:Video:update}
user_profile:
    path: /profile
    defaults: { _controller: TalentBundle:Talent:viewProfile}
update_profile:
    path: /profile/edit{id}
    defaults: {_controller: TalentBundle:Talent:updateProfile}
list_profile:
    path: /admin/list_profiles
    defaults: {_controller: TalentBundle:Talent:list}
delete_user:
    path: /admin/delete_user/{id}
    defaults: {_controller: TalentBundle:Talent:delete}
view_videos:
    path: /videos
    defaults: {_controller: TalentBundle:Video:View}
add_user:
    path: /admin/add_user
    defaults: {_controller: TalentBundle:Talent:add}