<?php

namespace AppBundle\Repository;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleRepository extends \Doctrine\ORM\EntityRepository
{
    public function orderTitle()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AppBundle:article p  ORDER BY p.title ASC')
            ->getResult();
    }
}
