<?php

namespace AppBundle\Repository;

/**
 * event_participantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class event_participantRepository extends \Doctrine\ORM\EntityRepository
{
}
