<?php

namespace AppBundle\Repository;

/**
 * order_lineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class order_lineRepository extends \Doctrine\ORM\EntityRepository
{
}
