<?php

namespace AppBundle\Repository;

/**
 * productRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByArray($array){
        $qb= $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.id in (:array)')
            ->setParameter('array',$array);
        return $qb->getQuery()->getResult();
    }

    public function findById($id){


       $qb=$this->getEntityManager()
           ->createQuery("select p from AppBundle:product p where p.id=:id")
           ->setParameter('id',$id);

        return $qb->getResult();

    }
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM AppBundle:product p
                WHERE p.productName LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

    public function countquantity(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT IDENTITY(ol.product) as product_id,sum(ol.quantity) FROM AppBundle:order_line ol GROUP BY ol.product'
            )
            ->getResult();
    }

    public function findProductNameForOneProduct($id){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.productName
            FROM AppBundle:product p
            WHERE p.id=:id'
            )
            ->setParameter('id',$id)
            ->getResult();
    }
}
