<?php

namespace AppBundle\Repository;

/**
 * reviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function orderStartD()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AppBundle:review p  ORDER BY p.rating  ASC')
            ->getResult();
    }
}
