<?php

namespace AppBundle\Repository;

/**
 * updatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class updatesRepository extends \Doctrine\ORM\EntityRepository
{
}
