<?php

namespace AppBundle\Repository;

/**
 * videoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class videoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findVideo($id)
    {
        $qb = $this->getEntityManager()
            ->createQuery('SELECT v FROM AppBundle:video v WHERE v.user =:id ')->setParameter('id',$id);
        return $query = $qb->getResult();
    }
}
