Competition:
    resource: "@CompetitionBundle/Controller/DefaultController.php"
    type:     annotation
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"