blog_homepage:
    path:     /add
    defaults: { _controller: BlogBundle:Blog:add }
afficher:
    path:     /afficher
    defaults: { _controller: BlogBundle:Blog:afficher }
afficherfront:
    path:     /afficherfront
    defaults: { _controller: BlogBundle:Blog:afficherfront }
edit:
    path:     /edit/{id}
    defaults: { _controller: BlogBundle:Blog:edit }
delete:
    path: /delete/{id}
    defaults: { _controller: BlogBundle:Blog:delete }
ajouter:
    path: /ajouter
    defaults: { _controller: BlogBundle:Updates:ajouter }
affiche:
    path: /affiche
    defaults: { _controller: BlogBundle:Updates:affiche }
affichefront:
    path: /affichefront
    defaults: { _controller: BlogBundle:Updates:affichefront }
modifier:
    path:     /modifier/{id}
    defaults: { _controller: BlogBundle:Updates:modifier }
supprimer:
    path: /supprimer/{id}
    defaults: { _controller: BlogBundle:Updates:supprimer }

tri:
    path: /sort
    defaults: {_controller:BlogBundle:Blog:affichetri }
