review_homepage:
    path:     /review
    defaults: { _controller: ReviewBundle:reviews:AddReview }
review_show:
    path:     admin/review/show
    defaults: { _controller: ReviewBundle:reviews:affiche }
review_delete:
    path:     admin/review/delete/{id}
    defaults: { _controller: ReviewBundle:reviews:delete }
review_edit:
    path:     admin/review/edit/{id}
    defaults: { _controller: ReviewBundle:reviews:edit }
AddReclam:
    path:     /complaint/add
    defaults: { _controller: ReviewBundle:complaints:AddReclam }
affiche_reclam:
    path:     admin/complaint/show
    defaults: { _controller: ReviewBundle:complaints:affiche_reclam }
delete_reclam:
    path:     admin/complaint/delete/{id}
    defaults: { _controller: ReviewBundle:complaints:delete_reclam }
edit_reclam:
    path:     admin/complaint/edit/{id}
    defaults: { _controller: ReviewBundle:complaints:edit_reclam }
AddReviewUser:
    path:     /rate/new
    defaults: { _controller: ReviewBundle:ReviewUseer:AddReviewUser }
AddReclamUser:
    path:     /complaint/new
    defaults: { _controller: ReviewBundle:ComplaintUser:AddReclamUser }
Mail:
    path:     /Mail/{id}
    defaults: { _controller: ReviewBundle:complaints:sendMessage }
affichetri:
    path:     /affichetri
    defaults: { _controller: ReviewBundle:reviews:tri }
filter_Rating:
    path:     /Rating/filter
    defaults: { _controller: ReviewBundle:reviews:filter }